
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.3
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.3",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  username: 'username',
  password: 'password',
  role: 'role',
  dosenId: 'dosenId',
  mahasiswaId: 'mahasiswaId',
  prodiId: 'prodiId',
  nickname: 'nickname',
  avatarUrl: 'avatarUrl',
  email: 'email',
  noHp: 'noHp',
  statusVerifikasiEmail: 'statusVerifikasiEmail',
  statusVerifikasiWa: 'statusVerifikasiWa',
  googleDriveConnected: 'googleDriveConnected',
  googleAccessToken: 'googleAccessToken',
  googleRefreshToken: 'googleRefreshToken',
  googleTokenExpiry: 'googleTokenExpiry',
  wajibLengkapiProfil: 'wajibLengkapiProfil',
  firstLoginAt: 'firstLoginAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.VerifikasiOtpScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  jenis: 'jenis',
  kodeOtp: 'kodeOtp',
  dikirimPada: 'dikirimPada',
  kadaluarsaPada: 'kadaluarsaPada',
  status: 'status'
};

exports.Prisma.ActivityLogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  aktivitas: 'aktivitas',
  modul: 'modul',
  waktu: 'waktu',
  ipAddress: 'ipAddress'
};

exports.Prisma.ImportLogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  jenisData: 'jenisData',
  jumlahBaris: 'jumlahBaris',
  status: 'status',
  catatanError: 'catatanError',
  waktu: 'waktu'
};

exports.Prisma.TahunAkademikScalarFieldEnum = {
  id: 'id',
  kode: 'kode',
  nama: 'nama',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.KalenderAkademikScalarFieldEnum = {
  id: 'id',
  tahunAkademikId: 'tahunAkademikId',
  namaKegiatan: 'namaKegiatan',
  jenisKegiatan: 'jenisKegiatan',
  tanggalMulai: 'tanggalMulai',
  tanggalSelesai: 'tanggalSelesai',
  keterangan: 'keterangan',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SesiWaktuScalarFieldEnum = {
  id: 'id',
  kodeSesi: 'kodeSesi',
  jamMulai: 'jamMulai',
  jamSelesai: 'jamSelesai',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProdiScalarFieldEnum = {
  id: 'id',
  kodeProdi: 'kodeProdi',
  namaProdi: 'namaProdi',
  jenjang: 'jenjang',
  ketuaProdiId: 'ketuaProdiId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.KelasScalarFieldEnum = {
  id: 'id',
  prodiId: 'prodiId',
  namaKelas: 'namaKelas',
  angkatan: 'angkatan',
  tahunKurikulumId: 'tahunKurikulumId',
  semesterBerjalan: 'semesterBerjalan',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DosenScalarFieldEnum = {
  id: 'id',
  nidn: 'nidn',
  nama: 'nama',
  status: 'status',
  prodiId: 'prodiId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MahasiswaScalarFieldEnum = {
  id: 'id',
  nim: 'nim',
  nama: 'nama',
  kelasId: 'kelasId',
  prodiId: 'prodiId',
  jenisKelamin: 'jenisKelamin',
  tempatLahir: 'tempatLahir',
  tanggalLahir: 'tanggalLahir',
  periodeMasuk: 'periodeMasuk',
  jalurPendaftaran: 'jalurPendaftaran',
  status: 'status',
  dosenWaliId: 'dosenWaliId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RiwayatStatusMahasiswaScalarFieldEnum = {
  id: 'id',
  mahasiswaId: 'mahasiswaId',
  tahunAkademikId: 'tahunAkademikId',
  status: 'status',
  keterangan: 'keterangan',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RuanganScalarFieldEnum = {
  id: 'id',
  kodeRuangan: 'kodeRuangan',
  namaRuangan: 'namaRuangan',
  kapasitas: 'kapasitas',
  gedung: 'gedung',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TahunKurikulumScalarFieldEnum = {
  id: 'id',
  prodiId: 'prodiId',
  tahun: 'tahun',
  statusAktif: 'statusAktif',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MataKuliahScalarFieldEnum = {
  id: 'id',
  prodiId: 'prodiId',
  tahunKurikulumId: 'tahunKurikulumId',
  kodeMk: 'kodeMk',
  namaMk: 'namaMk',
  sks: 'sks',
  semester: 'semester',
  sifat: 'sifat',
  prasyaratId: 'prasyaratId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.JadwalScalarFieldEnum = {
  id: 'id',
  matakuliahId: 'matakuliahId',
  kelasId: 'kelasId',
  dosenId: 'dosenId',
  ruanganId: 'ruanganId',
  metode: 'metode',
  hari: 'hari',
  jamMulai: 'jamMulai',
  jamSelesai: 'jamSelesai',
  semester: 'semester',
  tahunAkademikId: 'tahunAkademikId',
  tahunKurikulumId: 'tahunKurikulumId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MengajarScalarFieldEnum = {
  id: 'id',
  jadwalId: 'jadwalId',
  dosenId: 'dosenId',
  matakuliahId: 'matakuliahId',
  kelasId: 'kelasId',
  semester: 'semester',
  tahunAkademikId: 'tahunAkademikId',
  totalPertemuan: 'totalPertemuan',
  deskripsiMk: 'deskripsiMk',
  bobotKehadiran: 'bobotKehadiran',
  bobotTugas: 'bobotTugas',
  bobotUts: 'bobotUts',
  bobotUas: 'bobotUas',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PertemuanScalarFieldEnum = {
  id: 'id',
  mengajarId: 'mengajarId',
  keBerapa: 'keBerapa',
  tanggal: 'tanggal',
  waktuMulai: 'waktuMulai',
  waktuSelesai: 'waktuSelesai',
  jenisPertemuan: 'jenisPertemuan',
  kelompok: 'kelompok',
  metodePembelajaran: 'metodePembelajaran',
  ruangKuliah: 'ruangKuliah',
  keteranganRuang: 'keteranganRuang',
  urlKuliahOnline: 'urlKuliahOnline',
  rencanaMateri: 'rencanaMateri',
  realisasiMateri: 'realisasiMateri',
  status: 'status',
  skemaPresensi: 'skemaPresensi',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MateriScalarFieldEnum = {
  id: 'id',
  pertemuanId: 'pertemuanId',
  judul: 'judul',
  deskripsi: 'deskripsi',
  jenis: 'jenis',
  urlAtauLink: 'urlAtauLink',
  gdriveFileId: 'gdriveFileId',
  gdriveOwnerUserId: 'gdriveOwnerUserId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MateriVideoQuestionScalarFieldEnum = {
  id: 'id',
  materiId: 'materiId',
  timestamp: 'timestamp',
  pertanyaan: 'pertanyaan',
  pilihan: 'pilihan',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MateriVideoProgressScalarFieldEnum = {
  id: 'id',
  materiId: 'materiId',
  mahasiswaId: 'mahasiswaId',
  completed: 'completed',
  lastTimestamp: 'lastTimestamp',
  videoDuration: 'videoDuration',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MateriAksesScalarFieldEnum = {
  id: 'id',
  materiId: 'materiId',
  mahasiswaId: 'mahasiswaId',
  waktuAkses: 'waktuAkses'
};

exports.Prisma.TugasScalarFieldEnum = {
  id: 'id',
  pertemuanId: 'pertemuanId',
  judul: 'judul',
  kategori: 'kategori',
  deskripsi: 'deskripsi',
  gdriveFileIdLampiran: 'gdriveFileIdLampiran',
  gdriveOwnerUserId: 'gdriveOwnerUserId',
  bankTugasId: 'bankTugasId',
  tanggalBuka: 'tanggalBuka',
  tanggalTutup: 'tanggalTutup',
  status: 'status',
  bobotNilai: 'bobotNilai',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TugasSubmissionScalarFieldEnum = {
  id: 'id',
  tugasId: 'tugasId',
  mahasiswaId: 'mahasiswaId',
  gdriveFileIdJawaban: 'gdriveFileIdJawaban',
  gdriveLink: 'gdriveLink',
  waktuSubmit: 'waktuSubmit',
  nilai: 'nilai',
  catatanDosen: 'catatanDosen',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BankTugasScalarFieldEnum = {
  id: 'id',
  dosenId: 'dosenId',
  matakuliahId: 'matakuliahId',
  judul: 'judul',
  kategori: 'kategori',
  deskripsi: 'deskripsi',
  fileUrl: 'fileUrl',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.KuisScalarFieldEnum = {
  id: 'id',
  pertemuanId: 'pertemuanId',
  mengajarId: 'mengajarId',
  tipeUjian: 'tipeUjian',
  judul: 'judul',
  jenis: 'jenis',
  deskripsi: 'deskripsi',
  bobotNilai: 'bobotNilai',
  waktuMulai: 'waktuMulai',
  waktuSelesai: 'waktuSelesai',
  durasiMenit: 'durasiMenit',
  modeLockdown: 'modeLockdown',
  bankKuisId: 'bankKuisId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BankKuisScalarFieldEnum = {
  id: 'id',
  dosenId: 'dosenId',
  matakuliahId: 'matakuliahId',
  judul: 'judul',
  tipeUjian: 'tipeUjian',
  jenis: 'jenis',
  deskripsi: 'deskripsi',
  bobotNilai: 'bobotNilai',
  modeLockdown: 'modeLockdown',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BankKuisSoalScalarFieldEnum = {
  id: 'id',
  bankKuisId: 'bankKuisId',
  tipeSoal: 'tipeSoal',
  pertanyaan: 'pertanyaan',
  pilihanJawaban: 'pilihanJawaban',
  kunciJawaban: 'kunciJawaban',
  fileUrl: 'fileUrl',
  bobotSoal: 'bobotSoal',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.KuisSoalScalarFieldEnum = {
  id: 'id',
  kuisId: 'kuisId',
  tipeSoal: 'tipeSoal',
  pertanyaan: 'pertanyaan',
  pilihanJawaban: 'pilihanJawaban',
  kunciJawaban: 'kunciJawaban',
  fileUrl: 'fileUrl',
  bobotSoal: 'bobotSoal',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.KuisJawabanScalarFieldEnum = {
  id: 'id',
  kuisId: 'kuisId',
  mahasiswaId: 'mahasiswaId',
  soalId: 'soalId',
  jawaban: 'jawaban',
  nilaiSoal: 'nilaiSoal',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.KuisAttemptScalarFieldEnum = {
  id: 'id',
  kuisId: 'kuisId',
  mahasiswaId: 'mahasiswaId',
  waktuMulai: 'waktuMulai',
  waktuSelesai: 'waktuSelesai',
  status: 'status',
  alasanDitutupPaksa: 'alasanDitutupPaksa',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.NilaiAkhirScalarFieldEnum = {
  id: 'id',
  mengajarId: 'mengajarId',
  mahasiswaId: 'mahasiswaId',
  nilaiTugas: 'nilaiTugas',
  nilaiKuis: 'nilaiKuis',
  nilaiUts: 'nilaiUts',
  nilaiUas: 'nilaiUas',
  nilaiAkhir: 'nilaiAkhir',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.NotifikasiWaLogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  jenisNotifikasi: 'jenisNotifikasi',
  pesan: 'pesan',
  statusKirim: 'statusKirim',
  waktuKirim: 'waktuKirim'
};

exports.Prisma.PresensiScalarFieldEnum = {
  id: 'id',
  pertemuanId: 'pertemuanId',
  mahasiswaId: 'mahasiswaId',
  status: 'status',
  waktu: 'waktu'
};

exports.Prisma.DiskusiScalarFieldEnum = {
  id: 'id',
  pertemuanId: 'pertemuanId',
  userId: 'userId',
  materiId: 'materiId',
  tugasId: 'tugasId',
  isiPesan: 'isiPesan',
  parentId: 'parentId',
  waktu: 'waktu'
};

exports.Prisma.ChatRoomScalarFieldEnum = {
  id: 'id',
  type: 'type',
  name: 'name',
  createdBy: 'createdBy',
  createdAt: 'createdAt'
};

exports.Prisma.ChatMemberScalarFieldEnum = {
  id: 'id',
  roomId: 'roomId',
  userId: 'userId',
  role: 'role',
  joinedAt: 'joinedAt'
};

exports.Prisma.ChatMessageScalarFieldEnum = {
  id: 'id',
  roomId: 'roomId',
  senderId: 'senderId',
  message: 'message',
  createdAt: 'createdAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.UserOrderByRelevanceFieldEnum = {
  username: 'username',
  password: 'password',
  nickname: 'nickname',
  avatarUrl: 'avatarUrl',
  email: 'email',
  noHp: 'noHp',
  googleAccessToken: 'googleAccessToken',
  googleRefreshToken: 'googleRefreshToken'
};

exports.Prisma.VerifikasiOtpOrderByRelevanceFieldEnum = {
  kodeOtp: 'kodeOtp'
};

exports.Prisma.ActivityLogOrderByRelevanceFieldEnum = {
  aktivitas: 'aktivitas',
  modul: 'modul',
  ipAddress: 'ipAddress'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.ImportLogOrderByRelevanceFieldEnum = {
  jenisData: 'jenisData'
};

exports.Prisma.TahunAkademikOrderByRelevanceFieldEnum = {
  kode: 'kode',
  nama: 'nama'
};

exports.Prisma.KalenderAkademikOrderByRelevanceFieldEnum = {
  namaKegiatan: 'namaKegiatan',
  keterangan: 'keterangan'
};

exports.Prisma.SesiWaktuOrderByRelevanceFieldEnum = {
  kodeSesi: 'kodeSesi',
  jamMulai: 'jamMulai',
  jamSelesai: 'jamSelesai'
};

exports.Prisma.ProdiOrderByRelevanceFieldEnum = {
  kodeProdi: 'kodeProdi',
  namaProdi: 'namaProdi',
  jenjang: 'jenjang'
};

exports.Prisma.KelasOrderByRelevanceFieldEnum = {
  namaKelas: 'namaKelas'
};

exports.Prisma.DosenOrderByRelevanceFieldEnum = {
  nidn: 'nidn',
  nama: 'nama'
};

exports.Prisma.MahasiswaOrderByRelevanceFieldEnum = {
  nim: 'nim',
  nama: 'nama',
  tempatLahir: 'tempatLahir',
  periodeMasuk: 'periodeMasuk',
  jalurPendaftaran: 'jalurPendaftaran'
};

exports.Prisma.RiwayatStatusMahasiswaOrderByRelevanceFieldEnum = {
  keterangan: 'keterangan'
};

exports.Prisma.RuanganOrderByRelevanceFieldEnum = {
  kodeRuangan: 'kodeRuangan',
  namaRuangan: 'namaRuangan',
  gedung: 'gedung'
};

exports.Prisma.MataKuliahOrderByRelevanceFieldEnum = {
  kodeMk: 'kodeMk',
  namaMk: 'namaMk'
};

exports.Prisma.JadwalOrderByRelevanceFieldEnum = {
  metode: 'metode',
  hari: 'hari',
  jamMulai: 'jamMulai',
  jamSelesai: 'jamSelesai'
};

exports.Prisma.MengajarOrderByRelevanceFieldEnum = {
  deskripsiMk: 'deskripsiMk'
};

exports.Prisma.PertemuanOrderByRelevanceFieldEnum = {
  waktuMulai: 'waktuMulai',
  waktuSelesai: 'waktuSelesai',
  jenisPertemuan: 'jenisPertemuan',
  kelompok: 'kelompok',
  metodePembelajaran: 'metodePembelajaran',
  ruangKuliah: 'ruangKuliah',
  keteranganRuang: 'keteranganRuang',
  urlKuliahOnline: 'urlKuliahOnline',
  rencanaMateri: 'rencanaMateri',
  realisasiMateri: 'realisasiMateri'
};

exports.Prisma.MateriOrderByRelevanceFieldEnum = {
  judul: 'judul',
  deskripsi: 'deskripsi',
  urlAtauLink: 'urlAtauLink',
  gdriveFileId: 'gdriveFileId'
};

exports.Prisma.MateriVideoQuestionOrderByRelevanceFieldEnum = {
  pertanyaan: 'pertanyaan'
};

exports.Prisma.TugasOrderByRelevanceFieldEnum = {
  judul: 'judul',
  kategori: 'kategori',
  deskripsi: 'deskripsi',
  gdriveFileIdLampiran: 'gdriveFileIdLampiran'
};

exports.Prisma.TugasSubmissionOrderByRelevanceFieldEnum = {
  gdriveFileIdJawaban: 'gdriveFileIdJawaban',
  gdriveLink: 'gdriveLink',
  catatanDosen: 'catatanDosen'
};

exports.Prisma.BankTugasOrderByRelevanceFieldEnum = {
  judul: 'judul',
  kategori: 'kategori',
  deskripsi: 'deskripsi',
  fileUrl: 'fileUrl'
};

exports.Prisma.KuisOrderByRelevanceFieldEnum = {
  judul: 'judul',
  deskripsi: 'deskripsi'
};

exports.Prisma.BankKuisOrderByRelevanceFieldEnum = {
  judul: 'judul',
  deskripsi: 'deskripsi'
};

exports.Prisma.BankKuisSoalOrderByRelevanceFieldEnum = {
  pertanyaan: 'pertanyaan',
  kunciJawaban: 'kunciJawaban',
  fileUrl: 'fileUrl'
};

exports.Prisma.KuisSoalOrderByRelevanceFieldEnum = {
  pertanyaan: 'pertanyaan',
  kunciJawaban: 'kunciJawaban',
  fileUrl: 'fileUrl'
};

exports.Prisma.KuisJawabanOrderByRelevanceFieldEnum = {
  jawaban: 'jawaban'
};

exports.Prisma.KuisAttemptOrderByRelevanceFieldEnum = {
  alasanDitutupPaksa: 'alasanDitutupPaksa'
};

exports.Prisma.NotifikasiWaLogOrderByRelevanceFieldEnum = {
  jenisNotifikasi: 'jenisNotifikasi',
  pesan: 'pesan',
  statusKirim: 'statusKirim'
};

exports.Prisma.DiskusiOrderByRelevanceFieldEnum = {
  isiPesan: 'isiPesan'
};

exports.Prisma.ChatRoomOrderByRelevanceFieldEnum = {
  name: 'name'
};

exports.Prisma.ChatMessageOrderByRelevanceFieldEnum = {
  message: 'message'
};
exports.Role = exports.$Enums.Role = {
  ADMIN: 'ADMIN',
  ADMIN_AKADEMIK: 'ADMIN_AKADEMIK',
  ADMIN_PRODI: 'ADMIN_PRODI',
  DOSEN: 'DOSEN',
  MAHASISWA: 'MAHASISWA'
};

exports.VerifikasiStatus = exports.$Enums.VerifikasiStatus = {
  BELUM: 'BELUM',
  TERVERIFIKASI: 'TERVERIFIKASI'
};

exports.OtpJenis = exports.$Enums.OtpJenis = {
  EMAIL: 'EMAIL',
  WHATSAPP: 'WHATSAPP'
};

exports.OtpStatus = exports.$Enums.OtpStatus = {
  PENDING: 'PENDING',
  BERHASIL: 'BERHASIL',
  GAGAL: 'GAGAL'
};

exports.ImportStatus = exports.$Enums.ImportStatus = {
  SUKSES: 'SUKSES',
  SEBAGIAN: 'SEBAGIAN',
  GAGAL: 'GAGAL'
};

exports.StatusAkademik = exports.$Enums.StatusAkademik = {
  AKTIF: 'AKTIF',
  NONAKTIF: 'NONAKTIF'
};

exports.JenisKegiatanAkademik = exports.$Enums.JenisKegiatanAkademik = {
  AWAL_KULIAH: 'AWAL_KULIAH',
  UTS: 'UTS',
  UAS: 'UAS',
  LIBUR: 'LIBUR',
  LAINNYA: 'LAINNYA'
};

exports.StatusAktif = exports.$Enums.StatusAktif = {
  AKTIF: 'AKTIF',
  NONAKTIF: 'NONAKTIF'
};

exports.JenisKelamin = exports.$Enums.JenisKelamin = {
  L: 'L',
  P: 'P'
};

exports.StatusMahasiswa = exports.$Enums.StatusMahasiswa = {
  AKTIF: 'AKTIF',
  NONAKTIF: 'NONAKTIF',
  LULUS: 'LULUS',
  DO: 'DO',
  MENGUNDURKAN_DIRI: 'MENGUNDURKAN_DIRI',
  CUTI: 'CUTI'
};

exports.SifatMk = exports.$Enums.SifatMk = {
  WAJIB: 'WAJIB',
  PILIHAN: 'PILIHAN'
};

exports.StatusPertemuan = exports.$Enums.StatusPertemuan = {
  BELUM: 'BELUM',
  MULAI: 'MULAI',
  SELESAI: 'SELESAI',
  TERLAKSANA: 'TERLAKSANA'
};

exports.SkemaPresensi = exports.$Enums.SkemaPresensi = {
  SINKRONUS: 'SINKRONUS',
  ASINKRONUS: 'ASINKRONUS'
};

exports.JenisMateri = exports.$Enums.JenisMateri = {
  DOKUMEN: 'DOKUMEN',
  LINK: 'LINK',
  VIDEO: 'VIDEO'
};

exports.StatusTugas = exports.$Enums.StatusTugas = {
  OPEN: 'OPEN',
  CLOSE: 'CLOSE'
};

exports.TipeUjian = exports.$Enums.TipeUjian = {
  KUIS: 'KUIS',
  UTS: 'UTS',
  UAS: 'UAS'
};

exports.JenisKuis = exports.$Enums.JenisKuis = {
  PILIHAN_GANDA: 'PILIHAN_GANDA'
};

exports.TipeSoal = exports.$Enums.TipeSoal = {
  SINGLE_CHOICE: 'SINGLE_CHOICE',
  MULTIPLE_CHOICE: 'MULTIPLE_CHOICE'
};

exports.StatusAttempt = exports.$Enums.StatusAttempt = {
  SEDANG_MENGERJAKAN: 'SEDANG_MENGERJAKAN',
  SELESAI: 'SELESAI',
  DITUTUP_PAKSA: 'DITUTUP_PAKSA'
};

exports.StatusKehadiran = exports.$Enums.StatusKehadiran = {
  HADIR: 'HADIR',
  SAKIT: 'SAKIT',
  IZIN: 'IZIN',
  ALPA: 'ALPA'
};

exports.ChatRoomType = exports.$Enums.ChatRoomType = {
  PERSONAL: 'PERSONAL',
  GROUP: 'GROUP',
  CLASS: 'CLASS'
};

exports.ChatMemberRole = exports.$Enums.ChatMemberRole = {
  MEMBER: 'MEMBER',
  ADMIN: 'ADMIN'
};

exports.Prisma.ModelName = {
  User: 'User',
  VerifikasiOtp: 'VerifikasiOtp',
  ActivityLog: 'ActivityLog',
  ImportLog: 'ImportLog',
  TahunAkademik: 'TahunAkademik',
  KalenderAkademik: 'KalenderAkademik',
  SesiWaktu: 'SesiWaktu',
  Prodi: 'Prodi',
  Kelas: 'Kelas',
  Dosen: 'Dosen',
  Mahasiswa: 'Mahasiswa',
  RiwayatStatusMahasiswa: 'RiwayatStatusMahasiswa',
  Ruangan: 'Ruangan',
  TahunKurikulum: 'TahunKurikulum',
  MataKuliah: 'MataKuliah',
  Jadwal: 'Jadwal',
  Mengajar: 'Mengajar',
  Pertemuan: 'Pertemuan',
  Materi: 'Materi',
  MateriVideoQuestion: 'MateriVideoQuestion',
  MateriVideoProgress: 'MateriVideoProgress',
  MateriAkses: 'MateriAkses',
  Tugas: 'Tugas',
  TugasSubmission: 'TugasSubmission',
  BankTugas: 'BankTugas',
  Kuis: 'Kuis',
  BankKuis: 'BankKuis',
  BankKuisSoal: 'BankKuisSoal',
  KuisSoal: 'KuisSoal',
  KuisJawaban: 'KuisJawaban',
  KuisAttempt: 'KuisAttempt',
  NilaiAkhir: 'NilaiAkhir',
  NotifikasiWaLog: 'NotifikasiWaLog',
  Presensi: 'Presensi',
  Diskusi: 'Diskusi',
  ChatRoom: 'ChatRoom',
  ChatMember: 'ChatMember',
  ChatMessage: 'ChatMessage'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
